# Generated by Django 4.2.4 on 2024-05-03 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="WagerBids",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wager_user_type",
                    models.CharField(
                        choices=[
                            ("wager_bidder", "wager_bidder"),
                            ("wager_accepter", "wager_accepter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("wager_amount", models.DecimalField(decimal_places=4, max_digits=12)),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "wager_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
